### ISSUE TITLE
Empty genomicVariations.json

### ISSUE THREAD

**Issue by jLebioda** [GenomicDataInfrastructure/starter-kit-beacon2-ri-api#1]
Hi! It appears that the contents of the file https://github.com/GenomicDataInfrastructure/starter-kit-beacon2-ri-api/blob/master/deploy/data/genomicVariations.json were deleted in one of the recent commits: https://github.com/GenomicDataInfrastructure/starter-kit-beacon2-ri-api/commit/1d8e00c7c167fdf1fa41c7095fccbaf429e09867#diff-d13e2711ccc0a26b6048847c23823bc3328f064526fc2011189fcda248ff1093

Moreover, there is probably a typo in https://github.com/GenomicDataInfrastructure/starter-kit-beacon2-ri-api/blob/master/deploy/README.md?plain=1#L41 - the filename should be genomicVariations.json

**Comment by costero-e** [comment]
Hi @jLebioda and thank you for the post.
The genomicVariations.json file you are referring was removed a lot of time ago and uses an old schema that the new Beacon does not support anymore. But I now updated the repo with a genomicVariations.json file with synthetic data that fits to new schema and can be used, if that works for you.

**Comment by jLebioda** [comment]
Dear Oriol,
thanks for your update. That resolves the issue.
I'd like to ask you - are you aware of existence of any documentation that describes how to create the json files from real genomic files?

PS. please note that there's still a typo in L41 of deploy/README.MD:
```
docker cp /path/to/genomicVariationsVcf.json deploy_db_1:tmp/genomicVariations.json
here -------------------------------^^^
```

**Comment by costero-e** [comment]
Hi @jLebioda,
thank you for the reply and for spotting the typo! I will fix it.
Related to your question, in EGA we developed a tool that comes out of the box within this beacon repository but also has its own repository here [beacon-ri-tools](https://github.com/EGA-archive/beacon2-ri-tools).
If you go there you will find all the instructions to deploy and convert data from vcf to json files.
I don't know if this answer helped you, don't hesitate to ask if you have any other doubt.

**Comment by jLebioda** [comment]
Yes it's very helpful, many thanks! :)
